# all-playbooks.yml

---
  - import_playbook: ./playbooks/update-packages.yml
  - import_playbook: ./playbooks/install-service.yml
  - import_playbook: ./playbooks/check-httpd-status.yml
  - import_playbook: ./playbooks/firewalld-configuration.yml
  - import_playbook: ./playbooks/change-ifname.yml
  - import_playbook: ./playbooks/nmcli-stop.yml
  - import_playbook: ./playbooks/cofigure_index_html.yml
    