# firewalld-configuration.yml

---
  - hosts: webservers
    become: true
    become_method: sudo
    tasks:
      - name: Run firewalld service
        service: 
          name: firewalld 
          state: started
          enabled: yes
        notify: Reload service firewalld

      - name: Allow web traffic
        firewalld:
          service: http
          permanent: true
          state: enabled
        notify: Reload service firewalld

      - name: Open port 80
        firewalld:
          port: 80/tcp
          permanent: true
          state: enabled
        notify: Reload service firewalld

    handlers: 
      - name: Reload service firewalld
        service:
          name: firewalld
          state: restarted
      
