# all-playbooks.yml

---    
  - name: install apache and ftp
    hosts: webservers
    become: true
    become_method: sudo
    collections: 
    - ansible.posix.selinux
    
    roles:
      - apache
      - vsftpd
    
