# all-playbooks.yml

---    
  - name: install apache and ftp
    hosts: webservers
    become: true
    become_method: sudo

    pre_tasks:
      collections:
        - name: ansible.posix

    roles:
      - apache
      - vsftpd
    
