# all-playbooks.yml

---
  - name: install apache and ftp
  # - name: install apache and ftp
    # hosts: webservers
    hosts: node1
    become: true
    # become_method: sudo

    roles:
      # - apache
      - vsftpd
    