---
  - name: Run firewalld service
    service: name=firewalld state=started enabled=yes
    notify: Restart service firewalld

  - name: Allow ftp traffic
    firewalld: service=ftp permanent=true state=enabled immediate=true
    notify: Restart service firewalld

  - name: Allow ftp traffic
    firewalld: port=20/tcp permanent=true state=enabled immediate=true
    notify: Restart service firewalld